spring:
  application:
    name: eureka-client-service

eureka:
    client:
      serviceUrl:
        defaultZone: https://**********.appspot.com/eureka


# eureka:
#   client:
#     register-with-eureka: true
#     fetch-registry: true
#     service-url:
#       defaultZone: http://localhost:8761/eureka/
#   instance:
#     hostname: localhost
