spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/alban-okoby/configserver.git
          search-paths: medtrack
          default-label: main
server:
  port: 8888
